### ISSUE TITLE
누가 무슨일 할까요?

### ISSUE THREAD

**Issue by MinSooJoh** [dahee-diana96/cowork-practice#3]
해야할 일:

1. fizzbuzz

2. introduce

**Comment by MinSooJoh** [comment]
저는 나가기 전까지 이래저래 도울 수 있는 일은 도와드릴께요.

**Comment by jaechanjo** [comment]
지금 그러니까 develop은 각자 만들면 된다는 걸까요?

**Comment by MinSooJoh** [comment]
각자 무슨 작업 하실지 정하시죠. 하시고 싶은 일 있으세요? 재찬씨 현서씨?

**Comment by MinSooJoh** [comment]
네 그런거 같아요

**Comment by jaechanjo** [comment]
그럼 저는 fizzbuzz하겠습니다

**Comment by hyunseogu** [comment]
그럼 introduce 하겠습니다

**Comment by MinSooJoh** [comment]
거기서 피쳐 피즈버즈
하시면 될거 같네요

**Comment by MinSooJoh** [comment]
msjoh@MINsLAPTOP MINGW64 ~/My Documents/dev/flow_practice (develop)
$ git flow feature start fizzbuzz
Switched to a new branch 'feature/fizzbuzz'

Summary of actions:
- A new branch 'feature/fizzbuzz' was created, based on 'develop'
- You are now on branch 'feature/fizzbuzz'

Now, start committing on your feature. When done, use:

     git flow feature finish fizzbuzz

**Comment by MinSooJoh** [comment]
현서님은 git flow feature start introduce 하시면 되겠네요 그럼

**Comment by MinSooJoh** [comment]
팀장님은 프로잭트 생성하셔야 할꺼 같아요.

**Comment by dahee-diana96** [comment]
현서님

- [x] introduce.md 작업

재찬님

- [x] fizzbuzz.py 작업

**Comment by dahee-diana96** [comment]
이렇게 하면 되려나용?

**Comment by MinSooJoh** [comment]
상단에 Projects 탭에서 생성하셔야 할듯
유튭 20:14 팀장의 기다리는 동안 할 일과 풀리퀘검토
참고하시면 될듯..

**Comment by jaechanjo** [comment]
fizzbuzz Done! please review about it!

**Comment by dahee-diana96** [comment]
둘 다 approve 완료했습니당
